Repository jordanrigden/agile-web-project, pull requests merged in 2025-04, with the labels that each got.

#9 model and config file
  config.py
  models.py
Labels: documentation

#11 app of phase 1
  app.py
Labels: documentation

#15 basic intro file
  templates/intro.html
Labels: documentation, enhancement, question

#25 feat: add login.html template
  templates/login.html
Labels: documentation

#26 feat: add register.html template
  templates/register.html
Labels: documentation

#22 login and register logic
  app.py
  templates/share.html
  templates/shared_with_me.html
  templates/upload.html
Labels: bug, documentation, help wanted, question

#27 Fixed missing tag of <form> & <div> in the login form
  templates/login.html
Labels: bug, documentation, invalid

#29 Add workout upload and visualization features
  app.py
Labels: documentation, enhancement

#32 feat: create data visualization with charts.js
  templates/visualize.html
Labels: documentation, enhancement

#33 modern, clean and sporty web page(css style)
  static/css/style.css
Labels: enhancement

#35 fix: updated base.html to correct navbar routing
  templates/base.html
Labels: bug, documentation, enhancement, question

#36 add the title of the intro page
  templates/intro.html
Labels: documentation
