Repository jordanrigden/agile-web-project, pull requests merged in 2025-05, with the labels that each got.

#60 Enhance FitTrack homepage title: larger font, icon, and glow effect
  app.py
  static/css/style.css
  templates/intro.html
  templates/login.html
  templates/register.html
  templates/share.html
Labels: documentation, enhancement

#61 delete the project structure
  README.md
  static/css/style.css
  templates/intro.html
  templates/share.html
Labels: documentation, enhancement

#67 Enhance form validation with stricter rules and detailed error messages
  forms.py
Labels: enhancement

#71 Add unit test for RegisterForm
  tests/test_registration.py
Labels: documentation, question

#73 Add unittest for the test form
  tests/test_form.py
Labels: documentation, question

#76 Add unit test for login form
  tests/test_login.py
Labels: documentation, question

#79 Add New Unit Test for app.py Python File
  tests/test_app.py
  tests/test_workout.py
Labels: bug, documentation

#84 Add unit test for share form
  tests/test_share.py
Labels: documentation, question

#88 Add New Unit Test for model.py Python File
  tests/test_models.py
Labels: documentation

#87 Add unit test for weight update form
  tests/test_weight_update.py
Labels: documentation

#92 Add selenium test for the upload
  tests/selenium/test_selenium_upload.py
Labels: documentation

#90 Add Selenium Test for Login form
  tests/selenium/test_selenium_login.py
Labels: documentation

#98 Add selenium test for share
  tests/selenium/test_selenium_share.py
Labels: documentation

#97 Add Unit test for test_selenium_logout.py file
  tests/selenium/test_selenium_logout.py
Labels: documentation, enhancement

#100 Moving the selenium rgister file to the selenium folder
  tests/selenium/test_selenium_register.py
Labels: documentation

#105 add live Flask server support to all Selenium test files
  tests/selenium/server_utils.py
  tests/selenium/test_selenium_a_register.py
  tests/selenium/test_selenium_b_login.py
  tests/selenium/test_selenium_c_logout.py
  tests/selenium/test_selenium_d_upload.py
  tests/selenium/test_selenium_e_visualize.py
  tests/selenium/test_selenium_f_share.py
Labels: enhancement

#111 Add "Run Successful" Printable Message to Unit Test
  tests/selenium/test_selenium_a_register.py
  tests/test_app.py
  tests/test_form.py
  tests/test_login.py
  tests/test_models.py
  tests/test_registration.py
  tests/test_share.py
  tests/test_weight_update.py
  tests/test_workout.py
Labels: documentation, enhancement

#112 Adding messages for successful selenium testing
  tests/selenium/test_selenium_a_register.py
  tests/selenium/test_selenium_b_login.py
  tests/selenium/test_selenium_c_logout.py
  tests/selenium/test_selenium_d_upload.py
  tests/selenium/test_selenium_e_visualize.py
  tests/selenium/test_selenium_f_share.py
Labels: enhancement

#115 complete the README file
  README.md
Labels: documentation, enhancement
